spring.application.name=praveenatechcompany


spring.mongodb.database= employeeonboarding-db
spring.mongodb.uri=mongodb+srv://praveenaexpense:praveena1406@cluster0.r0r8az6.mongodb.net/?appName=Cluster0
